window.OSavePresentation = {
  presentationDate: "16 July 2026",
  videoSrc: "",
  videoEmbedUrl: "https://drive.google.com/file/d/1qkeE5kPh6L4RRLE-_LyiFysJ5LogNIo7/preview",
  companies: {
    rooch: { title: "Group Oversight", category: "Strategic Direction & Core Governance", logo: "assets/logos/rooch.png", description: "ROOCH Holding Inc. serves as the foundational parent entity, providing strategic corporate governance, key capital allocation, and group-wide operational synergy.", highlights: [{ icon: "&#128737;", title: "Strategic Capitalization", text: "Empowering fast-growing subsidiaries with robust financial resources and scaling pathways to dominate local markets." }, { icon: "&#128200;", title: "Diversified Synergy", text: "Balancing operational risk and compound growth across civil construction, retail FMCG logistics, and enterprise software suites." }] },
    vertex: { title: "Vertex Technologies", category: "Enterprise Software & Cloud Platforms", logo: "assets/logos/vertex.png", description: "Creators of enterprise ERP software, eLGU digitization systems, Dealerover SaaS portals, and customized municipal database architectures.", highlights: [{ icon: "&#128187;", title: "eLGU Digitization", text: "Active across 50+ municipal portals, digitizing tax clearance, permit approvals, and public records." }, { icon: "&#9881;", title: "Dealerover SaaS", text: "Automating heavy machinery dealer operations, equipment leasing schedules, and parts inventories." }] },
    hanvins: { title: "Hanvins Construction", category: "Civil Infrastructure & Public Works", logo: "assets/logos/hanvin.png", description: "Delivering robust infrastructure, public highway connections, commercial plazas, and municipal development designs across regions.", highlights: [{ icon: "&#127959;", title: "Large-Scale Portfolio", text: "PHP 250M+ active project pipeline encompassing private commercial builds and municipal civil works." }, { icon: "&#128176;", title: "Banking Partner Funding Expansion", text: "Requesting PHP 153M in capital upgrades for fleet expansion and batching plant acquisition." }] },
    men2solutions: { title: "MEN2 Solutions", category: "Manpower Sourcing & Talent Acquisition", logo: "assets/logos/men2.png", description: "Specialized corporate staffing and labor supply provider, sourcing high-caliber professionals, skilled industrial workers, and operational personnel across group subsidiaries.", highlights: [{ icon: "&#128101;", title: "Strategic Staffing", text: "Managing group-wide staffing needs, recruitment drives, and human resource scaling pathways." }, { icon: "&#128295;", title: "Labor Allocation", text: "Providing immediate skilled labor support to construction (Hanvins) and logistics (MEN2) operations." }] },
    men2dagupan: { title: "MEN2 Dagupan", category: "North Luzon Logistics & Supply", logo: "assets/logos/men2.png", description: "Primary northern logistics hub, coordinating regional FMCG distribution pipelines and Mama Pina's food cargo dispatch.", highlights: [{ icon: "&#128666;", title: "North Supply Authority", text: "PHP 45M+ annual volume, servicing major outlets across Region 1, 2, and CAR." }, { icon: "&#128230;", title: "Mama Pina's Synergy", text: "Direct distribution integration with Pangasinan noodle processing units." }] },
    men2marikina: { title: "MEN2 Marikina", category: "NCR & South Luzon Logistics", logo: "assets/logos/men2.png", description: "Southern distribution anchor, managing regional warehouse dispatch and automated retail replenishment.", highlights: [{ icon: "&#127981;", title: "NCR Replenishment", text: "PHP 68M+ annual volume, servicing Metro Manila and Calabarzon retail networks." }, { icon: "&#9889;", title: "Dealerover Sync", text: "Real-time middleware routing schedules trigger rapid deliveries." }] },
    mamapina: { title: "Mama Pina's Food Brand", category: "Traditional Recipes & Consumer Foods", logo: "assets/logos/mama-pina.png", description: "Beloved traditional food brand celebrated for local recipes, high-quality noodle products, and high customer retention. Directly integrated with MEN2 logistics.", highlights: [{ icon: "&#127829;", title: "Consumer Favorite", text: "Famous for traditional quality noodles, generating high customer loyalty and brand retention." }, { icon: "&#127807;", title: "Integrated Distribution", text: "Directly synchronized with MEN2 logistics network to supply local supermarkets and O!Save discount stores." }] },
    jcbs: { title: "JCBS / MEN2 Industrial", category: "Industrial Business & Engineering", logo: "assets/logos/jcbs.png", description: "Specialized service division focused on industrial plant services, boiler/extruder operations, heavy machinery uptime, and key partnerships to scale manufacturing infrastructure.", highlights: [{ icon: "&#127959;", title: "Industrial Services", text: "Uptime management for boilers, extruders, and facility manufacturing lines." }, { icon: "&#9875;", title: "Logistics Partnerships", text: "Successfully integrated fuel logistics and compliance with Sea Oil Philippines Inc." }] }
  },
  achievements: [
    { group: "Tech & Solutions", title: "VOS ERP Suite", subtitle: "VERTEX - Consolidated Accounting & Inventory", image: "assets/achievements/vos-erp-source.png", caption: "VERTEX (VOS ERP Suite): Active in corporate subsidiaries. Handles over Php 250M of consolidated transactions annually. Projected annual profit is Php 52M." },
    { group: "Tech & Solutions", title: "Dealerover Sync", subtitle: "VERTEX - Stock Matching & Dispatch", image: "assets/achievements/dealerover-sync-source.jpg", caption: "VERTEX (Dealerover Sync): Branch stock matching & dispatch. Scales monthly subscription rates across roving dealers in Pangasinan. Projected annual profit is Php 8.4M." },
    { group: "Tech & Solutions", title: "eLGU Digitalization", subtitle: "VERTEX - Municipal Treasury Tax & Permits", image: "assets/achievements/elgu-deployment-source.jpg", caption: "VERTEX (eLGU Digitalization): Deployed in Mapandan and municipal councils. Digitizes permits and local taxes. Projected profit is Php 15M per town deployment." },
    { group: "Tech & Solutions", title: "SFA & Core Systems", subtitle: "VERTEX - Mobile Sales, HRIS, & Custom ERP", image: "assets/achievements/sfa-booking-source.jpg", caption: "VERTEX (SFA & Core Systems): Deployed SFA mobile booking. HRIS (Php 2M per deployment) and Aircon ERP (Php 800k per deployment) custom installations." },
    { group: "Infra & Energy", title: "LGU Mapandan Solar", subtitle: "Hanvin - Solar grid deployment", image: "assets/achievements/lgu-mapandan-source.jpeg", caption: "LGU Mapandan Solar: Completed high-capacity solar grid installation project, serving as the model site for group green energy integration." },
    { group: "Infra & Energy", title: "La Sallette Solar", subtitle: "Hanvin - Campus solar offset", image: "assets/achievements/la-sallette-source.png", caption: "La Sallette Solar: High-throughput school campus solar deployment completed, delivering off-grid power offsets for academic classrooms." },
    { group: "Infra & Energy", title: "Men2 Dagupan Warehouse", subtitle: "Hanvin - Logistics facility shell", image: "assets/achievements/men2-warehouse-source.png", caption: "MEN2 Warehouse Manila: Completed logistics facility shell design and structural foundation engineering in Metro Manila." },
    { group: "Infra & Energy", title: "Men2 Dagupan Offices", subtitle: "Hanvin - Office interior & facade", image: "assets/achievements/men2-offices-source.png", caption: "MEN2 Offices Manila: Delivered completed corporate office interior fit-out and modern exterior building facade." },
    { group: "FMCG & Logistics", title: "Foodsphere Frozen", subtitle: "MEN2 Dagupan - La Union", image: "assets/achievements/foodsphere-source.jpg", caption: "MEN2 Dagupan: Successfully engaged with Foodsphere Inc. (Frozen) in La Union, securing storage and distribution operations." },
    { group: "FMCG & Logistics", title: "Dealerover Opening", subtitle: "MEN2 Dagupan - San Carlos", image: "assets/achievements/dealerover-opening-source.jpg", caption: "MEN2 Dagupan (Dealerover Launch): First live opening of Dealerover digital middleware tracking routines in San Carlos, syncing logistics." },
    { group: "FMCG & Logistics", title: "Kopiko Engagement", subtitle: "MEN2 Dagupan - Pangasinan", image: null, caption: "MEN2 Dagupan: Successfully engaged with ECOSSENTIALS FOODS CORP (KOPIKO) in Pangasinan to handle regional food trade distribution." },
    { group: "FMCG & Logistics", title: "Sea Oil Engagement", subtitle: "JCBS Industrial - Industrial Business", image: "assets/achievements/sea-oil-source.jpg", caption: "JCBS / MEN2 Industrial: Successfully engaged with Sea Oil Philippines Inc. for specialized fuel transport and storage integrations." },
    { group: "FMCG & Logistics", title: "Federated Onboarding", subtitle: "MEN2 Manila - Commenced Mar 2026", image: null, caption: "MEN2 Manila (Federated): Commenced regional distribution partnership in March 2026, targeting a potential volume of 6M." },
    { group: "FMCG & Logistics", title: "Fitrite Integration", subtitle: "MEN2 Manila - Commenced Mar 2026", image: null, caption: "MEN2 Manila (Fitrite): Commenced brand distribution in March 2026, with an estimated potential volume of 3-5M." },
    { group: "FMCG & Logistics", title: "Indomie Mi Goreng", subtitle: "MEN2 Manila - Commenced Feb 2026", image: null, caption: "MEN2 Manila (Indomie Mi Goreng): Commenced product logistics and regional supply distribution in February 2026, targeting a potential volume of 2M." },
    { group: "FMCG & Logistics", title: "Prime Flavors (Primo)", subtitle: "MEN2 Manila - NCR Rollout", image: null, caption: "MEN2 Manila (Prime Flavors): Secured distribution rights and commenced regional distribution rollouts for Primo Gulaman products in NCR." },
    { group: "FMCG & Logistics", title: "Dever Energy", subtitle: "MEN2 Manila - Commenced Jun 2026", image: "assets/achievements/dever-source.jpg", caption: "MEN2 Manila (Dever Energy): Commenced brand distribution and logistics operations for Dever Energy Products in June 2026." }
  ],
  oilDemand: [
    ["Plaridel, Bulacan", 6888], ["Pampanga Province", 4980], ["Naga & Kawit, Cavite", 4320],
    ["Villasis, Pangasinan", 3840], ["Meycauayan, Bulacan", 3408], ["Nueva Ecija", 3360], ["Taytay, Rizal", 840]
  ],
  pancitWarehouses: [
    ["PLR", "Plaridel", 35714], ["PMP", "Pampanga", 35714], ["NAG", "Naga & Kawit", 35714],
    ["VIL", "Villasis", 35714], ["MEY", "Meycauayan", 35714], ["NVE", "Nueva Ecija", 35714], ["TAY", "Taytay", 35716]
  ],
  oilCapacity: [
    { label: "Palm Oil 350mL", growth: "+336%", current: [12600, 7200, 19800, 594000], expanded: [43200, 43200, 86400, 2592000] },
    { label: "Palm Oil 1L", growth: "+157%", current: [4800, 3600, 8400, 252000], expanded: [10800, 10800, 21600, 648000] },
    { label: "Canola Oil 1L", growth: "+157%", current: [4800, 3600, 8400, 252000], expanded: [10800, 10800, 21600, 648000] }
  ],
  oilCycle: [["Purchase order", "5d"], ["Weekly shipment", "7d"], ["Warehouse", "8d"], ["Production", "1d"], ["Delivery to O!Save", "3d"], ["Collection", "45d"]],
  pancitCycle: [["Bulk purchase", "Quarterly"], ["Warehouse", "Materials"], ["Production", "Daily"], ["Delivery", "Daily"], ["O!Save sales", "Retail"], ["Collection", "45d"], ["Reinvestment", "Repeat"]]
};
